### ISSUE TITLE
Feat: 프론트엔드에서 토론방 관련 필요한 API 추가

### ISSUE THREAD

**Issue by Richter3766** [KnowckknowcK/BE#34]
### ✨ 기능 리스트
- [x] 댓글 수 카운트 기능
- [x] 메세지 좋아요 수 카운트 기능
- [x] 기타 프론트에서 필요한 기능
---

### ✏ 사용 이유

프론트엔드의 요구사항에 맞춰 API를 개선하기 위함입니다.

---

**Comment by adorableco** [comment]
헉 제가 실수로 브랜치 이름을 #34 로 먼저 만들었군요..... ㅠㅠ
